---
- name: Configure host
  hosts: localhost
  become: true
  gather_facts: false

  pre_tasks:
    - name: Update package cache
      ansible.builtin.package:
        update_cache: true

  roles:
    - role: .
