---
# tasks file for ansible_role_tlp
- name: Set OS specific variables
  ansible.builtin.include_vars: "{{ vars_file }}"
  when: vars_file is file
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  vars:
    vars_file: "{{ item }}"
