---
# tasks file for ansible_role_template
- name: Ensure ansible_facts used by role
  when: not ansible_facts.keys() | list |
    intersect(required_facts) == required_facts
  ansible.builtin.setup:
    gather_subset: min

- name: Set OS specific variables
  ansible.builtin.include_vars: "{{ vars_file }}"
  when: vars_file is file
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  vars:
    vars_file: "{{ item }}"
